// screens/admin/ReportsScreen.tsx
import React, { useState, useContext } from 'react';
import { View, Text, StyleSheet, Pressable, Alert, ScrollView, ActivityIndicator } from 'react-native';
import dayjs from 'dayjs';
import DateTimePicker from '@react-native-community/datetimepicker';
import { generateAttendancePDF } from '../../utils/pdf';
import { listBatches, listStudentsByBatch, getAttendanceByDate } from '../../db/queries';
import { AuthContext } from '../../context/AuthContext';
import Card from '../../components/Card';
import { lightTheme } from '../../theme/light';
import { Ionicons } from '@expo/vector-icons';

export default function ReportsScreen() {
  const s = lightTheme;
  const { user, logout } = useContext(AuthContext);
  const [from, setFrom] = useState(new Date());
  const [to, setTo] = useState(new Date());
  const [showFrom, setShowFrom] = useState(false);
  const [showTo, setShowTo] = useState(false);
  const [generating, setGenerating] = useState(false);

  const buildHTML = async () => {
    const batches = await listBatches();
    const fromDate = dayjs(from).format('YYYY-MM-DD');
    const toDate = dayjs(to).format('YYYY-MM-DD');
    
    let html = `
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #3B82F6; text-align: center; }
          .header { text-align: center; margin-bottom: 30px; }
          .date-range { color: #666; font-size: 14px; }
          .batch-section { margin-bottom: 40px; page-break-inside: avoid; }
          h2 { color: #1F2937; border-bottom: 2px solid #3B82F6; padding-bottom: 5px; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; }
          th { background-color: #3B82F6; color: white; padding: 10px; text-align: left; }
          td { padding: 10px; border-bottom: 1px solid #E5E7EB; }
          tr:nth-child(even) { background-color: #F9FAFB; }
          .present { color: #10B981; font-weight: bold; }
          .absent { color: #EF4444; font-weight: bold; }
          .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>📊 Attendance Report</h1>
          <p class="date-range">Period: ${dayjs(from).format('DD MMM YYYY')} to ${dayjs(to).format('DD MMM YYYY')}</p>
          <p class="date-range">Generated on: ${dayjs().format('DD MMM YYYY, hh:mm A')}</p>
        </div>
    `;
    
    for (const batch of batches) {
      html += `
        <div class="batch-section">
          <h2>Batch: ${batch.batchName} (${batch.batchId})</h2>
          <table>
            <thead>
              <tr>
                <th>PRN</th>
                <th>Student Name</th>
                <th>Date</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
      `;
      
      const students = await listStudentsByBatch(batch.batchId);
      
      // Get attendance for date range
      let currentDate = dayjs(from);
      while (currentDate.isBefore(dayjs(to)) || currentDate.isSame(dayjs(to))) {
        const dateStr = currentDate.format('YYYY-MM-DD');
        const attendanceRecords: any[] = await getAttendanceByDate(dateStr);
        
        for (const student of students) {
          const studentPrn = (student as any).prn;
          const studentName = (student as any).name;
          const record = attendanceRecords.find((r: any) => r.studentPrn === studentPrn);
          const status = record ? (record.status as string) : 'Not Marked';
          const statusClass = status === 'Present' ? 'present' : status === 'Absent' ? 'absent' : '';
          
          html += `
            <tr>
              <td>${studentPrn}</td>
              <td>${studentName}</td>
              <td>${currentDate.format('DD MMM YYYY')}</td>
              <td class="${statusClass}">${status}</td>
            </tr>
          `;
        }
        
        currentDate = currentDate.add(1, 'day');
      }
      
      html += `
            </tbody>
          </table>
        </div>
      `;
    }
    
    html += `
        <div class="footer">
          <p>Smart Attendance System • Generated by ${user?.username}</p>
        </div>
      </body>
      </html>
    `;
    
    return html;
  };

  const generate = async () => {
    if (dayjs(from).isAfter(dayjs(to))) {
      Alert.alert('Invalid Date Range', 'Start date cannot be after end date');
      return;
    }

    setGenerating(true);
    try {
      const html = await buildHTML();
      await generateAttendancePDF(html);
      Alert.alert('Success', 'PDF report generated and ready to share');
    } catch (error) {
      console.error('Error generating report:', error);
      Alert.alert('Error', 'Failed to generate report. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleLogout = () => {
    Alert.alert(
      'Logout',
      'Are you sure you want to logout?',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Logout', 
          style: 'destructive',
          onPress: async () => await logout()
        },
      ]
    );
  };

  return (
    <View style={{ flex: 1, backgroundColor: s.colors.background }}>
      {/* Top Bar with Logo and Logout */}
      <View style={styles.topBar}>
        <View style={styles.userSection}>
          <View style={styles.logoContainer}>
            <Ionicons name="finger-print" size={28} color={s.colors.primary} />
          </View>
          <View>
            <Text style={styles.appTitle}>Smart Attendance</Text>
            <Text style={styles.userInfo}>{user?.username} • {user?.role}</Text>
          </View>
        </View>
        <Pressable style={styles.logoutButton} onPress={handleLogout}>
          <Ionicons name="log-out-outline" size={22} color={s.colors.danger} />
          <Text style={styles.logoutText}>Logout</Text>
        </Pressable>
      </View>

      <ScrollView style={styles.container}>
        {/* Header Card */}
        <Card style={styles.headerCard}>
          <View style={styles.header}>
            <View style={styles.headerIcon}>
              <Ionicons name="document-text" size={32} color={s.colors.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.title}>Generate Reports</Text>
              <Text style={styles.subtitle}>Create attendance reports for any date range</Text>
            </View>
          </View>
        </Card>

        {/* Date Selection Card */}
        <Card style={styles.dateCard}>
          <Text style={styles.sectionTitle}>Select Date Range</Text>
          
          {/* From Date */}
          <View style={styles.dateSection}>
            <Text style={styles.dateLabel}>Start Date</Text>
            <Pressable style={styles.dateButton} onPress={() => setShowFrom(true)}>
              <Ionicons name="calendar" size={20} color={s.colors.primary} />
              <Text style={styles.dateButtonText}>{dayjs(from).format('DD MMM YYYY')}</Text>
              <Ionicons name="chevron-down" size={20} color={s.colors.subtext} />
            </Pressable>
          </View>

          {/* To Date */}
          <View style={styles.dateSection}>
            <Text style={styles.dateLabel}>End Date</Text>
            <Pressable style={styles.dateButton} onPress={() => setShowTo(true)}>
              <Ionicons name="calendar" size={20} color={s.colors.primary} />
              <Text style={styles.dateButtonText}>{dayjs(to).format('DD MMM YYYY')}</Text>
              <Ionicons name="chevron-down" size={20} color={s.colors.subtext} />
            </Pressable>
          </View>

          {/* Duration Info */}
          <View style={styles.durationInfo}>
            <Ionicons name="time-outline" size={16} color={s.colors.subtext} />
            <Text style={styles.durationText}>
              {dayjs(to).diff(dayjs(from), 'day') + 1} day{dayjs(to).diff(dayjs(from), 'day') !== 0 ? 's' : ''} selected
            </Text>
          </View>
        </Card>

        {/* Report Info Card */}
        <Card style={styles.infoCard}>
          <Text style={styles.infoTitle}>📄 Report Contents</Text>
          <View style={styles.infoItem}>
            <Ionicons name="checkmark-circle" size={20} color="#10B981" />
            <Text style={styles.infoText}>All batches and students</Text>
          </View>
          <View style={styles.infoItem}>
            <Ionicons name="checkmark-circle" size={20} color="#10B981" />
            <Text style={styles.infoText}>Daily attendance records</Text>
          </View>
          <View style={styles.infoItem}>
            <Ionicons name="checkmark-circle" size={20} color="#10B981" />
            <Text style={styles.infoText}>Present/Absent status</Text>
          </View>
          <View style={styles.infoItem}>
            <Ionicons name="checkmark-circle" size={20} color="#10B981" />
            <Text style={styles.infoText}>Professional PDF format</Text>
          </View>
        </Card>

        {/* Generate Button */}
        <Pressable 
          style={[styles.generateButton, generating && styles.generateButtonDisabled]} 
          onPress={generate}
          disabled={generating}
        >
          {generating ? (
            <>
              <ActivityIndicator color="#fff" />
              <Text style={styles.generateButtonText}>Generating...</Text>
            </>
          ) : (
            <>
              <Ionicons name="download-outline" size={22} color="#fff" />
              <Text style={styles.generateButtonText}>Generate PDF Report</Text>
            </>
          )}
        </Pressable>

        {/* Note Card */}
        <Card style={styles.noteCard}>
          <Ionicons name="information-circle-outline" size={20} color={s.colors.primary} />
          <Text style={styles.noteText}>
            The report will include all attendance data for the selected date range. 
            You can share or save the generated PDF.
          </Text>
        </Card>

        {showFrom && (
          <DateTimePicker 
            value={from} 
            mode="date" 
            onChange={(_, d) => { 
              setShowFrom(false); 
              if (d) setFrom(d); 
            }} 
          />
        )}
        
        {showTo && (
          <DateTimePicker 
            value={to} 
            mode="date" 
            onChange={(_, d) => { 
              setShowTo(false); 
              if (d) setTo(d); 
            }} 
          />
        )}
      </ScrollView>
    </View>
  );
}

const s = lightTheme;
const styles = StyleSheet.create({
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: s.colors.card,
    paddingHorizontal: s.spacing(2),
    paddingVertical: s.spacing(2),
    paddingTop: s.spacing(6),
    borderBottomWidth: 1,
    borderBottomColor: s.colors.border,
    shadowColor: s.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  userSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s.spacing(1.5),
  },
  logoContainer: {
    width: 48,
    height: 48,
    borderRadius: s.radius.md,
    backgroundColor: s.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: s.colors.text,
  },
  userInfo: {
    fontSize: 11,
    color: s.colors.subtext,
    marginTop: 2,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s.spacing(0.75),
    paddingHorizontal: s.spacing(2),
    paddingVertical: s.spacing(1.25),
    backgroundColor: s.colors.danger + '15',
    borderRadius: s.radius.md,
  },
  logoutText: {
    fontSize: 14,
    fontWeight: '600',
    color: s.colors.danger,
  },
  container: { 
    flex: 1, 
    backgroundColor: s.colors.background,
    padding: s.spacing(2),
  },
  headerCard: {
    marginBottom: s.spacing(2),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s.spacing(2),
  },
  headerIcon: {
    width: 64,
    height: 64,
    borderRadius: s.radius.md,
    backgroundColor: s.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: s.colors.text,
  },
  subtitle: {
    fontSize: 14,
    color: s.colors.subtext,
    marginTop: 4,
  },
  dateCard: {
    marginBottom: s.spacing(2),
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: s.colors.text,
    marginBottom: s.spacing(2),
  },
  dateSection: {
    marginBottom: s.spacing(2),
  },
  dateLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: s.colors.text,
    marginBottom: s.spacing(1),
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s.spacing(1.5),
    padding: s.spacing(2),
    backgroundColor: s.colors.background,
    borderRadius: s.radius.md,
    borderWidth: 1,
    borderColor: s.colors.border,
  },
  dateButtonText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: s.colors.text,
  },
  durationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s.spacing(1),
    padding: s.spacing(1.5),
    backgroundColor: s.colors.primary + '10',
    borderRadius: s.radius.sm,
  },
  durationText: {
    fontSize: 13,
    color: s.colors.text,
  },
  infoCard: {
    marginBottom: s.spacing(2),
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: s.colors.text,
    marginBottom: s.spacing(2),
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s.spacing(1.5),
    marginBottom: s.spacing(1.5),
  },
  infoText: {
    fontSize: 14,
    color: s.colors.text,
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s.spacing(1.5),
    backgroundColor: s.colors.primary,
    borderRadius: s.radius.md,
    padding: s.spacing(2.5),
    marginBottom: s.spacing(2),
    shadowColor: s.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  generateButtonDisabled: {
    opacity: 0.6,
  },
  generateButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  noteCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: s.spacing(1.5),
    backgroundColor: s.colors.primary + '10',
    marginBottom: s.spacing(2),
  },
  noteText: {
    flex: 1,
    fontSize: 13,
    color: s.colors.text,
    lineHeight: 18,
  },
});